"""added table relationships for class and race to character table

Revision ID: 01d64866767a
Revises: b9d2183f7257
Create Date: 2024-09-12 11:03:07.137388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d64866767a'
down_revision = 'b9d2183f7257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
