"""empty message

Revision ID: 05b71ecc4236
Revises: 59714e751f19
Create Date: 2024-09-25 14:46:23.693744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b71ecc4236'
down_revision = '59714e751f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_skill')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_skill',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('skill_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='fk_character_skill_character_id'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='fk_character_skill_skill_id'),
    sa.PrimaryKeyConstraint('id', name='pk_character_skill')
    )
    # ### end Alembic commands ###
