"""empty message

Revision ID: 0a255da5aabb
Revises: 241b9591bdfd
Create Date: 2024-09-14 18:43:41.166789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a255da5aabb'
down_revision = '241b9591bdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_rpg_system')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_rpg_system',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('rpg_system_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='fk_character_rpg_system_character_id'),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name='fk_character_rpg_system_rpg_system_id'),
    sa.PrimaryKeyConstraint('id', name='pk_character_rpg_system')
    )
    # ### end Alembic commands ###
