"""empty message

Revision ID: 0e10e1bf9e50
Revises: 4aed209268ef
Create Date: 2024-09-20 15:07:50.180823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e10e1bf9e50'
down_revision = '4aed209268ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='fk_character_item_character_id'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_character_item_item_id'),
    sa.PrimaryKeyConstraint('id', name='pk_character_item')
    )
    # ### end Alembic commands ###
