"""empty message

Revision ID: 1d8547a18fef
Revises: 31256896db04
Create Date: 2024-09-16 21:11:36.177404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8547a18fef'
down_revision = '31256896db04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spell', schema=None) as batch_op:
        batch_op.drop_column('damage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
