"""quick migration

Revision ID: 1f6ec7ffe4f1
Revises: 18fe1c8fa7c0
Create Date: 2024-09-07 21:49:52.048358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1f6ec7ffe4f1'
down_revision = '18fe1c8fa7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.drop_column('system_data')

    with op.batch_alter_table('character_homebrew_item', schema=None) as batch_op:
        batch_op.drop_column('system_data')

    with op.batch_alter_table('character_homebrew_skill', schema=None) as batch_op:
        batch_op.drop_column('system_data')

    with op.batch_alter_table('character_item', schema=None) as batch_op:
        batch_op.drop_column('system_data')

    with op.batch_alter_table('character_race', schema=None) as batch_op:
        batch_op.drop_column('race_data')

    with op.batch_alter_table('character_rpg_system', schema=None) as batch_op:
        batch_op.drop_column('ruleset_version')

    with op.batch_alter_table('character_skill', schema=None) as batch_op:
        batch_op.drop_column('system_data')

    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.alter_column('languages',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('natural_weapons',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.alter_column('natural_weapons',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('languages',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('character_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_data', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('character_rpg_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruleset_version', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('character_race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_data', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('character_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_data', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('character_homebrew_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_data', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('character_homebrew_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_data', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('character_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_data', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
