"""small changes to fix bugs

Revision ID: 241b9591bdfd
Revises: 3c4f0a323297
Create Date: 2024-09-13 21:07:35.071718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241b9591bdfd'
down_revision = '3c4f0a323297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_note_created_by', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_note_creator_id'), 'user', ['creator_id'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_note_creator_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_note_created_by', 'user', ['created_by'], ['id'])
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
