"""empty message

Revision ID: 26c78916d666
Revises: 5222c9e2ed9a
Create Date: 2024-09-16 16:18:32.993931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c78916d666'
down_revision = '5222c9e2ed9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=50), nullable=True),
    sa.Column('casting_time', sa.String(length=50), nullable=True),
    sa.Column('range', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('components', sa.String(length=100), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_spell_rpg_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spell'))
    )
    op.create_table('class_progression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('spell_slots', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_class_progression_class_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_progression'))
    )
    op.create_table('class_spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_class_spell_class_id')),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], name=op.f('fk_class_spell_spell_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_spell'))
    )
    op.create_table('spell_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('slots_available', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_spell_slot_character_id')),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_spell_slot_class_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spell_slot'))
    )
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_features', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_column('race_features')

    op.drop_table('spell_slot')
    op.drop_table('class_spell')
    op.drop_table('class_progression')
    op.drop_table('spell')
    # ### end Alembic commands ###
