"""initial migration

Revision ID: 2e456a640fba
Revises: 
Create Date: 2024-08-26 16:33:01.253930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '2e456a640fba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hit_die', sa.String(length=10), nullable=True),
    sa.Column('primary_ability', sa.String(length=50), nullable=True),
    sa.Column('armor_proficiencies', sa.String(length=255), nullable=True),
    sa.Column('weapon_proficiencies', sa.String(length=255), nullable=True),
    sa.Column('spellcasting', sa.Boolean(), nullable=True),
    sa.Column('subclass_options', sa.JSON(), nullable=True),
    sa.Column('resource_tracking', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('damage_type', sa.String(length=50), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('enchantment_level', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('slot_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(length=255), nullable=True),
    sa.Column('vision_type', sa.String(length=50), nullable=True),
    sa.Column('natural_weapons', sa.String(length=255), nullable=True),
    sa.Column('favored_class', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpg_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('edition', sa.String(length=50), nullable=True),
    sa.Column('core_rulebook', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('default_settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('associated_ability', sa.String(length=50), nullable=True),
    sa.Column('skill_category', sa.String(length=50), nullable=True),
    sa.Column('difficulty_class', sa.Integer(), nullable=True),
    sa.Column('requires_training', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.Column('gm_id', sa.Integer(), nullable=True),
    sa.Column('session_logs', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('world_setting', sa.String(length=255), nullable=True),
    sa.Column('house_rules', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gm_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('alignment', sa.String(length=20), nullable=True),
    sa.Column('background', sa.String(length=100), nullable=True),
    sa.Column('inventory_weight_limit', sa.Integer(), nullable=True),
    sa.Column('status_effects', sa.JSON(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('system_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homebrew_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('damage_type', sa.String(length=50), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('enchantment_level', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('slot_type', sa.String(length=50), nullable=True),
    sa.Column('system_data', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homebrew_monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('challenge_rating', sa.Float(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('legendary_actions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homebrew_npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('alignment', sa.String(length=20), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('motivations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homebrew_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('associated_ability', sa.String(length=50), nullable=False),
    sa.Column('skill_category', sa.String(length=50), nullable=True),
    sa.Column('difficulty_class', sa.Integer(), nullable=True),
    sa.Column('requires_training', sa.Boolean(), nullable=True),
    sa.Column('system_data', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('challenge_rating', sa.Float(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('legendary_actions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('alignment', sa.String(length=20), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('motivations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.Column('homebrew_monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['homebrew_monster_id'], ['homebrew_monster.id'], ),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('homebrew_npc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['homebrew_npc_id'], ['homebrew_npc.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('system_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['rpg_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_homebrew_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('homebrew_item_id', sa.Integer(), nullable=False),
    sa.Column('system_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['homebrew_item_id'], ['homebrew_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_homebrew_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('homebrew_skill_id', sa.Integer(), nullable=False),
    sa.Column('system_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['homebrew_skill_id'], ['homebrew_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('system_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('race_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['rpg_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_rpg_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('system_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('shared_with', sa.JSON(), nullable=True),
    sa.Column('related_entities', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('character_skill')
    op.drop_table('character_rpg_system')
    op.drop_table('character_race')
    op.drop_table('character_item')
    op.drop_table('character_homebrew_skill')
    op.drop_table('character_homebrew_item')
    op.drop_table('character_class')
    op.drop_table('campaign_npc')
    op.drop_table('campaign_monster')
    op.drop_table('npc')
    op.drop_table('monster')
    op.drop_table('homebrew_skills')
    op.drop_table('homebrew_npc')
    op.drop_table('homebrew_monster')
    op.drop_table('homebrew_items')
    op.drop_table('character')
    op.drop_table('campaign')
    op.drop_table('user')
    op.drop_table('skill')
    op.drop_table('rpg_system')
    op.drop_table('race')
    op.drop_table('item')
    op.drop_table('class')
    # ### end Alembic commands ###
