"""empty message

Revision ID: 35b36e23c1fa
Revises: 05b71ecc4236
Create Date: 2024-09-25 15:04:22.152861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b36e23c1fa'
down_revision = '05b71ecc4236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency_bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('initiative', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('initiative')
        batch_op.drop_column('proficiency_bonus')

    # ### end Alembic commands ###
