"""Test migration

Revision ID: 3c4f0a323297
Revises: aa33390fbc48
Create Date: 2024-09-12 22:45:48.852361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4f0a323297'
down_revision = 'aa33390fbc48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homebrew_npc', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homebrew_npc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
