"""empty message

Revision ID: 5222c9e2ed9a
Revises: 7050ab919dbb
Create Date: 2024-09-16 14:56:31.663528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5222c9e2ed9a'
down_revision = '7050ab919dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('associated_ability', sa.String(length=50), nullable=True),
    sa.Column('feat_category', sa.String(length=50), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_feat_rpg_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feat'))
    )
    op.create_table('character_feat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('feat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_feat_character_id')),
    sa.ForeignKeyConstraint(['feat_id'], ['feat.id'], name=op.f('fk_character_feat_feat_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_feat'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_feat')
    op.drop_table('feat')
    # ### end Alembic commands ###
