"""empty message

Revision ID: 7050ab919dbb
Revises: 0a255da5aabb
Create Date: 2024-09-15 23:05:14.115421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7050ab919dbb'
down_revision = '0a255da5aabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability_scores', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('ability_scores')

    # ### end Alembic commands ###
