"""empty message

Revision ID: 76886b1e4604
Revises: 26c78916d666
Create Date: 2024-09-16 16:32:01.946423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76886b1e4604'
down_revision = '26c78916d666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_progression_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_character_class_progression_id'), 'class_progression', ['class_progression_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_character_class_progression_id'), type_='foreignkey')
        batch_op.drop_column('class_progression_id')

    # ### end Alembic commands ###
