"""empty message

Revision ID: 82e0ed2ff81a
Revises: 323ceaea68c2
Create Date: 2024-09-16 18:00:07.785232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '82e0ed2ff81a'
down_revision = '323ceaea68c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_progression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_spells', sa.JSON(), nullable=True))
        batch_op.drop_column('spell_slots')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_progression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spell_slots', sqlite.JSON(), nullable=True))
        batch_op.drop_column('available_spells')

    # ### end Alembic commands ###
