"""initial migration

Revision ID: 87c21a6495c7
Revises: 
Create Date: 2024-09-09 21:31:59.153569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c21a6495c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homebrew_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('damage_type', sa.String(length=50), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('enchantment_level', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('slot_type', sa.String(length=50), nullable=True),
    sa.Column('system_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_homebrew_items_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homebrew_items'))
    )
    op.create_table('homebrew_monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('challenge_rating', sa.Float(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('legendary_actions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_homebrew_monster_rpg_system_id')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_homebrew_monster_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homebrew_monster'))
    )
    op.create_table('homebrew_npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('alignment', sa.String(length=20), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('motivations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_homebrew_npc_rpg_system_id')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_homebrew_npc_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homebrew_npc'))
    )
    op.create_table('homebrew_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('associated_ability', sa.String(length=50), nullable=False),
    sa.Column('skill_category', sa.String(length=50), nullable=True),
    sa.Column('difficulty_class', sa.Integer(), nullable=True),
    sa.Column('requires_training', sa.Boolean(), nullable=True),
    sa.Column('system_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_homebrew_skills_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homebrew_skills'))
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('damage_type', sa.String(length=50), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('enchantment_level', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('slot_type', sa.String(length=50), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_item_rpg_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    op.create_table('monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('challenge_rating', sa.Float(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('legendary_actions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_monster_rpg_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster'))
    )
    op.create_table('npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('alignment', sa.String(length=20), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('motivations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_npc_rpg_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_npc'))
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('vision_type', sa.String(length=50), nullable=True),
    sa.Column('natural_weapons', sa.Text(), nullable=True),
    sa.Column('favored_class', sa.String(length=50), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_race_rpg_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race'))
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('associated_ability', sa.String(length=50), nullable=True),
    sa.Column('skill_category', sa.String(length=50), nullable=True),
    sa.Column('difficulty_class', sa.Integer(), nullable=True),
    sa.Column('requires_training', sa.Boolean(), nullable=True),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_skill_rpg_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill'))
    )
    op.create_table('campaign_monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.Column('homebrew_monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_campaign_monster_campaign_id')),
    sa.ForeignKeyConstraint(['homebrew_monster_id'], ['homebrew_monster.id'], name=op.f('fk_campaign_monster_homebrew_monster_id')),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.id'], name=op.f('fk_campaign_monster_monster_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_monster'))
    )
    op.create_table('campaign_npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('homebrew_npc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_campaign_npc_campaign_id')),
    sa.ForeignKeyConstraint(['homebrew_npc_id'], ['homebrew_npc.id'], name=op.f('fk_campaign_npc_homebrew_npc_id')),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], name=op.f('fk_campaign_npc_npc_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_npc'))
    )
    op.create_table('character_campaign',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_character_campaign_campaign_id')),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_campaign_character_id')),
    sa.PrimaryKeyConstraint('character_id', 'campaign_id', name=op.f('pk_character_campaign'))
    )
    op.create_table('character_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_class_character_id')),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_character_class_class_id')),
    sa.ForeignKeyConstraint(['system_id'], ['rpg_system.id'], name=op.f('fk_character_class_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_class'))
    )
    op.create_table('character_homebrew_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('homebrew_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_homebrew_item_character_id')),
    sa.ForeignKeyConstraint(['homebrew_item_id'], ['homebrew_items.id'], name=op.f('fk_character_homebrew_item_homebrew_item_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_homebrew_item'))
    )
    op.create_table('character_homebrew_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('homebrew_skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_homebrew_skill_character_id')),
    sa.ForeignKeyConstraint(['homebrew_skill_id'], ['homebrew_skills.id'], name=op.f('fk_character_homebrew_skill_homebrew_skill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_homebrew_skill'))
    )
    op.create_table('character_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_item_character_id')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_character_item_item_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_item'))
    )
    op.create_table('character_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_race_character_id')),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name=op.f('fk_character_race_race_id')),
    sa.ForeignKeyConstraint(['system_id'], ['rpg_system.id'], name=op.f('fk_character_race_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_race'))
    )
    op.create_table('character_rpg_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('rpg_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_rpg_system_character_id')),
    sa.ForeignKeyConstraint(['rpg_system_id'], ['rpg_system.id'], name=op.f('fk_character_rpg_system_rpg_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_rpg_system'))
    )
    op.create_table('character_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_character_skill_character_id')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_character_skill_skill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_skill'))
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('shared_with', sa.JSON(), nullable=True),
    sa.Column('related_entities', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_note_campaign_id')),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_note_character_id')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_note_created_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    op.create_table('user_bookmarked_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_user_bookmarked_items_item_id')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_bookmarked_items_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'item_id', name=op.f('pk_user_bookmarked_items'))
    )
    op.create_table('user_bookmarked_monsters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.id'], name=op.f('fk_user_bookmarked_monsters_monster_id')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_bookmarked_monsters_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'monster_id', name=op.f('pk_user_bookmarked_monsters'))
    )
    op.create_table('user_bookmarked_npcs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], name=op.f('fk_user_bookmarked_npcs_npc_id')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_bookmarked_npcs_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'npc_id', name=op.f('pk_user_bookmarked_npcs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bookmarked_npcs')
    op.drop_table('user_bookmarked_monsters')
    op.drop_table('user_bookmarked_items')
    op.drop_table('note')
    op.drop_table('character_skill')
    op.drop_table('character_rpg_system')
    op.drop_table('character_race')
    op.drop_table('character_item')
    op.drop_table('character_homebrew_skill')
    op.drop_table('character_homebrew_item')
    op.drop_table('character_class')
    op.drop_table('character_campaign')
    op.drop_table('campaign_npc')
    op.drop_table('campaign_monster')
    op.drop_table('skill')
    op.drop_table('race')
    op.drop_table('npc')
    op.drop_table('monster')
    op.drop_table('item')
    op.drop_table('homebrew_skills')
    op.drop_table('homebrew_npc')
    op.drop_table('homebrew_monster')
    op.drop_table('homebrew_items')
    # ### end Alembic commands ###
