"""Added some join tables for bookmarked items, monsters, npcs

Revision ID: 92acde334dd6
Revises: c4db8c88b3aa
Create Date: 2024-09-01 13:41:58.778139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92acde334dd6'
down_revision = 'c4db8c88b3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bookmarked_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.create_table('user_bookmarked_monsters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'monster_id')
    )
    op.create_table('user_bookmarked_npcs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'npc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bookmarked_npcs')
    op.drop_table('user_bookmarked_monsters')
    op.drop_table('user_bookmarked_items')
    # ### end Alembic commands ###
