"""Test migration

Revision ID: aa33390fbc48
Revises: f42b865234e5
Create Date: 2024-09-12 22:45:38.103922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa33390fbc48'
down_revision = 'f42b865234e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homebrew_npc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homebrew_npc', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
