"""empty message

Revision ID: bcb3974a4594
Revises: f62130ec0645
Create Date: 2024-09-16 18:22:23.324707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb3974a4594'
down_revision = 'f62130ec0645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_progression_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_character_class_progression_id'), 'class_progression', ['class_progression_id'], ['id'])

    with op.batch_alter_table('class_progression', schema=None) as batch_op:
        batch_op.drop_constraint('fk_class_progression_character_id', type_='foreignkey')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_progression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_class_progression_character_id', 'character', ['character_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_character_class_progression_id'), type_='foreignkey')
        batch_op.drop_column('class_progression_id')

    # ### end Alembic commands ###
