"""Added background and alignment tables

Revision ID: c9def60ef652
Revises: 1d8547a18fef
Create Date: 2024-09-17 19:50:24.698254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9def60ef652'
down_revision = '1d8547a18fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('moral_axis', sa.String(length=20), nullable=True),
    sa.Column('ethical_axis', sa.String(length=20), nullable=True),
    sa.Column('system_specific_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['rpg_system.id'], name=op.f('fk_alignment_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alignment'))
    )
    op.create_table('background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('proficiencies', sa.JSON(), nullable=True),
    sa.Column('ability_score_increases', sa.JSON(), nullable=True),
    sa.Column('granted_feats', sa.JSON(), nullable=True),
    sa.Column('choosable_feats', sa.JSON(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('background_features', sa.JSON(), nullable=True),
    sa.Column('system_specific_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['rpg_system.id'], name=op.f('fk_background_system_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background'))
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.drop_column('background')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('description')

    op.drop_table('background')
    op.drop_table('alignment')
    # ### end Alembic commands ###
