"""removed join table between race and character tables

Revision ID: d53b882cdd75
Revises: 96e3f819ffd7
Create Date: 2024-09-10 20:31:08.502868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53b882cdd75'
down_revision = '96e3f819ffd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_race')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('physical_features', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_character_race_id'), 'race', ['race_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_character_race_id'), type_='foreignkey')
        batch_op.drop_column('physical_features')
        batch_op.drop_column('race_id')

    op.create_table('character_race',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('race_id', sa.INTEGER(), nullable=False),
    sa.Column('system_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='fk_character_race_character_id'),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name='fk_character_race_race_id'),
    sa.ForeignKeyConstraint(['system_id'], ['rpg_system.id'], name='fk_character_race_system_id'),
    sa.PrimaryKeyConstraint('id', name='pk_character_race')
    )
    # ### end Alembic commands ###
