"""empty message

Revision ID: e29fc7ea9dd2
Revises: 76886b1e4604
Create Date: 2024-09-16 16:53:50.806780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29fc7ea9dd2'
down_revision = '76886b1e4604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_progression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_class_progression_character_id'), 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_progression', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_class_progression_character_id'), type_='foreignkey')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###
